### ISSUE TITLE
Liens cassés page contact

### ISSUE THREAD

**Issue by eflrp** [EduWireApps/ynotes-website#25]
Bonjour,

Sur la [page contact](https://ynotes.fr/contact/), les liens pour accéder aux pages Instagram et Facebook ne fonctionnent pas.

![image](https://user-images.githubusercontent.com/59921587/159160045-a27b09c4-7a0c-4ab8-9d7f-097e74cc66ed.png)
![image](https://user-images.githubusercontent.com/59921587/159160058-198629a8-8d08-4ace-a21c-9da665455494.png)

Bonne journée,
EFLRP

**Comment by florian-lefebvre** [comment]
ça a l'air de fonctionner pour Facebook pour moi, @JsonLinesCode tu peux tester de cliquer sur le lien vers Facebook ?

**Comment by eflrp** [comment]
Merci pour votre retour rapide !
Je pense savoir d'où vient le "problème" pour Facebook, l'url a l'air d'être une url mobile car elle marche sur mon téléphone et si je retire le _m._ de l'url, la page se charge correctement sur mon ordinateur.

**Comment by florian-lefebvre** [comment]
Ah super merci ! Je vais régler ça rapidement
